-- ================================================================
-- UIU Advisor Student Appointment System — Database Schema
-- ================================================================
-- Generated by analyzing all project modules:
--   • Login Portal (index.html)
--   • Student Module  (dashboard, advisor-list, booking, queue-status)
--   • Advisor Module  (dashboard, appointment management, time management, statistics)
--   • Admin Module    (overview, manage advisors, manage students, appointment logs)
-- ================================================================

-- Drop existing tables (in reverse dependency order) for a clean setup
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS penalties;
DROP TABLE IF EXISTS queue_tokens;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS advisor_unavailable_dates;
DROP TABLE IF EXISTS availability_slots;
DROP TABLE IF EXISTS advisor_profiles;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS departments;

-- ================================================================
-- 1. DEPARTMENTS
-- ================================================================
-- Referenced by advisors and students (e.g. "Computer Science", "Engineering")
-- Seen in: booking.html filters, advisor-list.html, manage_advisor.html
CREATE TABLE departments (
    department_id   INT             AUTO_INCREMENT PRIMARY KEY,
    department_name VARCHAR(150)    NOT NULL UNIQUE,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================
-- 2. USERS  (unified login table — all three roles)
-- ================================================================
-- Seen in: index.html login form (email + password)
-- Roles:   student | advisor | admin
CREATE TABLE users (
    user_id         INT             AUTO_INCREMENT PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    password_hash   VARCHAR(255)    NOT NULL,
    role            ENUM('student', 'advisor', 'admin') NOT NULL,
    full_name       VARCHAR(150)    NOT NULL,
    is_active       TINYINT(1)      DEFAULT 1,          -- admin can block users
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ================================================================
-- 3. STUDENTS
-- ================================================================
-- Seen in: manage_students.html  (student_id like "0112210450", name, 
--          total appointments, missed count, status Blocked/Active)
-- Seen in: appointment_logs.html (student name, missed attempts)
-- Seen in: statistics — at-risk students table (student id like "STU-1842")
CREATE TABLE students (
    student_id      VARCHAR(20)     PRIMARY KEY,         -- university ID e.g. "0112210450"
    user_id         INT             NOT NULL UNIQUE,
    department_id   INT             NULL,
    status          ENUM('active', 'warned', 'blocked')  DEFAULT 'active',
    missed_count    INT             DEFAULT 0,
    total_appointments INT          DEFAULT 0,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id)        REFERENCES users(user_id)        ON DELETE CASCADE,
    FOREIGN KEY (department_id)  REFERENCES departments(department_id) ON DELETE SET NULL
);

-- ================================================================
-- 4. ADVISOR PROFILES
-- ================================================================
-- Seen in: manage_advisor.html (name, department, email, edit/delete)
-- Seen in: advisor-list.html   (name, title, next session, availability)
-- Seen in: student-dashboard   (current advisor name, dept, room)
-- Seen in: advisor dashboard   (office hours, active status)
CREATE TABLE advisor_profiles (
    advisor_id      INT             AUTO_INCREMENT PRIMARY KEY,
    user_id         INT             NOT NULL UNIQUE,
    department_id   INT             NULL,
    title           VARCHAR(100)    NULL,                 -- e.g. "Associate Professor"
    room_number     VARCHAR(50)     NULL,                 -- e.g. "512(A)"
    office_hours    VARCHAR(100)    NULL,                 -- e.g. "9:00 AM - 5:00 PM"
    is_available    TINYINT(1)      DEFAULT 1,            -- Available / Busy toggle
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id)        REFERENCES users(user_id)        ON DELETE CASCADE,
    FOREIGN KEY (department_id)  REFERENCES departments(department_id) ON DELETE SET NULL
);

-- ================================================================
-- 5. AVAILABILITY SLOTS  (weekly recurring)
-- ================================================================
-- Seen in: Time Management page (Monday 09:00-12:00, 14:00-17:00, etc.)
-- Advisors set per-day slots; students see them in booking calendar
CREATE TABLE availability_slots (
    slot_id         INT             AUTO_INCREMENT PRIMARY KEY,
    advisor_id      INT             NOT NULL,
    day_of_week     ENUM('Monday','Tuesday','Wednesday','Thursday',
                         'Friday','Saturday','Sunday') NOT NULL,
    start_time      TIME            NOT NULL,
    end_time        TIME            NOT NULL,
    is_active       TINYINT(1)      DEFAULT 1,            -- toggle per day
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (advisor_id)     REFERENCES advisor_profiles(advisor_id) ON DELETE CASCADE
);

-- ================================================================
-- 6. ADVISOR UNAVAILABLE DATES  (custom one-off blocks)
-- ================================================================
-- Seen in: Time Management page — "Custom Unavailable Times" tab
CREATE TABLE advisor_unavailable_dates (
    unavailable_id  INT             AUTO_INCREMENT PRIMARY KEY,
    advisor_id      INT             NOT NULL,
    unavailable_date DATE           NOT NULL,
    reason          VARCHAR(255)    NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (advisor_id)     REFERENCES advisor_profiles(advisor_id) ON DELETE CASCADE
);

-- ================================================================
-- 7. APPOINTMENTS
-- ================================================================
-- Core table — ties a student to an advisor on a specific date & time
-- Seen in: booking.html      (select date, time, confirm)
-- Seen in: appointment_logs  (student, advisor, date, outcome)
-- Seen in: advisor dashboard (today's appts count, pending, no-shows)
-- Seen in: admin overview    (total bookings, auto-canceled)
-- Seen in: statistics        (total, completed, missed, cancelled)
CREATE TABLE appointments (
    appointment_id  INT             AUTO_INCREMENT PRIMARY KEY,
    student_id      VARCHAR(20)     NOT NULL,
    advisor_id      INT             NOT NULL,
    appointment_date DATE           NOT NULL,
    appointment_time TIME           NOT NULL,
    purpose         VARCHAR(255)    NULL,                 -- e.g. "Course Add", "Course Advice"
    status          ENUM('booked','waiting','serving',
                        'completed','missed','cancelled',
                        'auto_cancelled')   DEFAULT 'booked',
    is_urgent       TINYINT(1)      DEFAULT 0,            -- "+2 urgent" in advisor dashboard
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id)     REFERENCES students(student_id)          ON DELETE CASCADE,
    FOREIGN KEY (advisor_id)     REFERENCES advisor_profiles(advisor_id)  ON DELETE CASCADE
);

-- ================================================================
-- 8. QUEUE TOKENS
-- ================================================================
-- Token-based queue system for each advisor on a given date
-- Seen in: booking.html       (token grid 1-8, red=taken, green=available)
-- Seen in: student-dashboard  (token number, progress: Booked→Waiting→Serving→Canceled)
-- Seen in: queue-status.html  (Now Serving #3, Available #5, est. wait)
-- Seen in: advisor appointment management (current token #03, next token #04)
CREATE TABLE queue_tokens (
    token_id        INT             AUTO_INCREMENT PRIMARY KEY,
    appointment_id  INT             NOT NULL UNIQUE,
    advisor_id      INT             NOT NULL,
    token_number    INT             NOT NULL,              -- sequential per advisor per day
    queue_date      DATE            NOT NULL,
    status          ENUM('available','booked','waiting',
                        'serving','completed','missed',
                        'cancelled')        DEFAULT 'available',
    estimated_wait_minutes INT      NULL,                  -- e.g. 15-20 min
    called_at       TIMESTAMP       NULL,                  -- when advisor calls "Next"
    served_at       TIMESTAMP       NULL,                  -- session start
    completed_at    TIMESTAMP       NULL,                  -- session end
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE,
    FOREIGN KEY (advisor_id)     REFERENCES advisor_profiles(advisor_id)  ON DELETE CASCADE,
    UNIQUE KEY unique_token_per_day (advisor_id, queue_date, token_number)
);

-- ================================================================
-- 9. DOCUMENTS
-- ================================================================
-- Seen in: student-dashboard ("Upload Documents" action)
-- Seen in: queue-status       ("Upload Documents" button)
-- Seen in: advisor appointment management ("Preview File" button)
CREATE TABLE documents (
    document_id     INT             AUTO_INCREMENT PRIMARY KEY,
    appointment_id  INT             NULL,
    student_id      VARCHAR(20)     NOT NULL,
    file_name       VARCHAR(255)    NOT NULL,
    file_path       VARCHAR(500)    NOT NULL,
    file_type       VARCHAR(50)     NULL,                  -- e.g. "pdf", "docx"
    file_size_bytes BIGINT          NULL,
    uploaded_at     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE SET NULL,
    FOREIGN KEY (student_id)     REFERENCES students(student_id)          ON DELETE CASCADE
);

-- ================================================================
-- 10. PENALTIES
-- ================================================================
-- Seen in: admin_overview.html     (Recent Penalty List — student ID, name, missed, status)
-- Seen in: manage_students.html    (Send Warning / Block buttons, missed count badge)
-- Seen in: statistics page         (At-Risk Students Alert — risk level High/Medium)
CREATE TABLE penalties (
    penalty_id      INT             AUTO_INCREMENT PRIMARY KEY,
    student_id      VARCHAR(20)     NOT NULL,
    penalty_type    ENUM('warning', 'block', 'unblock')   NOT NULL,
    issued_by       INT             NULL,                  -- admin user_id who issued it
    reason          VARCHAR(500)    NULL,
    missed_count_at_time INT        NULL,                  -- snapshot of missed count
    risk_level      ENUM('low', 'medium', 'high')         NULL,
    issued_at       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id)     REFERENCES students(student_id) ON DELETE CASCADE,
    FOREIGN KEY (issued_by)      REFERENCES users(user_id)       ON DELETE SET NULL
);

-- ================================================================
-- 11. MESSAGES
-- ================================================================
-- Seen in: advisor-list.html (Message button with red dot notification)
CREATE TABLE messages (
    message_id      INT             AUTO_INCREMENT PRIMARY KEY,
    sender_id       INT             NOT NULL,
    receiver_id     INT             NOT NULL,
    message_text    TEXT            NOT NULL,
    is_read         TINYINT(1)      DEFAULT 0,
    sent_at         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_id)      REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id)    REFERENCES users(user_id) ON DELETE CASCADE
);

-- ================================================================
-- SEED DATA — Departments
-- ================================================================
-- Pre-populate departments seen across all modules
INSERT INTO departments (department_name) VALUES
    ('Computer Science & Engineering'),
    ('Electrical & Electronic Engineering'),
    ('Civil Engineering'),
    ('Mathematics'),
    ('Business'),
    ('Engineering');

-- ================================================================
-- INDEXES for common query patterns
-- ================================================================
-- Student lookup by status (admin student monitoring)
CREATE INDEX idx_students_status ON students(status);

-- Appointment queries by date and advisor (booking, queue, dashboard)
CREATE INDEX idx_appointments_date ON appointments(appointment_date);
CREATE INDEX idx_appointments_advisor_date ON appointments(advisor_id, appointment_date);
CREATE INDEX idx_appointments_student ON appointments(student_id);
CREATE INDEX idx_appointments_status ON appointments(status);

-- Queue lookups (live queue status page)
CREATE INDEX idx_queue_advisor_date ON queue_tokens(advisor_id, queue_date);
CREATE INDEX idx_queue_status ON queue_tokens(status);

-- Availability lookups (booking page, advisor list)
CREATE INDEX idx_availability_advisor ON availability_slots(advisor_id, day_of_week);

-- Penalty history (admin monitoring)
CREATE INDEX idx_penalties_student ON penalties(student_id);

-- Message inbox queries
CREATE INDEX idx_messages_receiver ON messages(receiver_id, is_read);
